# Generated by Django 3.1.5 on 2021-01-21 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notification_type', models.CharField(max_length=50)),
                ('notified_person', models.CharField(max_length=50)),
                ('notification_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notification_type', models.CharField(max_length=50)),
                ('notified_person', models.CharField(max_length=50)),
                ('notification_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Notification4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notification_type', models.CharField(max_length=50)),
                ('notified_person', models.CharField(max_length=50)),
                ('notification_status', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameModel(
            old_name='Notification',
            new_name='Notification1',
        ),
    ]
