# Generated by Django 3.1.5 on 2021-01-22 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('new', '0002_auto_20210121_1817'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('notification_type', models.CharField(max_length=50)),
                ('notified_person', models.CharField(max_length=50)),
                ('notification_status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Notification1',
        ),
        migrations.DeleteModel(
            name='Notification2',
        ),
        migrations.DeleteModel(
            name='Notification3',
        ),
        migrations.DeleteModel(
            name='Notification4',
        ),
    ]
